language: objective-c
osx_image: xcode9.1
rvm:
    - 2.4.2
install:
    - gem install xcpretty
script:
    - xcodebuild -project Leetcode.xcodeproj -scheme "Leetcode" | xcpretty
after_success:
    - sleep 3
